version: '3'
services:
  documentserver:
    image: onlyoffice/4testing-documentserver:latest
    volumes:
      - ./bin/:/tmp
    entrypoint: ["cp", "-ra", "/var/www/onlyoffice/documentserver/server/FileConverter/bin/.", "/tmp"]
  convertion-testing:
    build: ./
    tty: true
    environment:
      - ENV S3_KEY ""
      - ENV S3_PRIVATE_KEY ""
      - ENV PALLADIUM_TOKEN ""
    command: ["rspec"]

