version: '3'
services:
  documentserver:
    image: "onlyoffice/4testing-documentserver-ee:${DOCSERVER_VERSION}"
    volumes:
      - ./bin/:/tmp
    entrypoint: ["cp", "-ra", "/var/www/onlyoffice/documentserver/server/FileConverter/bin/.", "/tmp"]
  x2t-testing:
    build: ./
    tty: true
    depends_on:
      - documentserver
    command: ["bundle", "exec", "rspec"]
